### ISSUE TITLE
SharpSK incompatible with RunesEnchant

### ISSUE THREAD

**Issue by ghost** [Sharpjaws/SharpSK#24]
SharpSK is incompatible with RunesEnchant :/
Can you fix it? (I can send u .jar of runes enchant)
https://www.spigotmc.org/resources/runesenchant-recoded-beta.19363/

```
[15:27:27 INFO]: This server is running Paper version git-Paper-1168 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
```

```
[15:26:20] [Server thread/INFO]: [SharpSK] Enabling SharpSK v1.6.2.2
[15:26:20] [Server thread/INFO]: [SharpSK] Generating config...
[15:26:20] [Server thread/INFO]: [SharpSK] Enabling Metrics...
[15:26:20] [Server thread/INFO]: [SharpSK] Metrics successfully enabled
[15:26:20] [Server thread/INFO]: [SharpSK] Attempting to register Addon...
[15:26:20] [Server thread/INFO]: [SharpSK] Attempting to register stuff...
[15:26:20] [Server thread/ERROR]: Error occurred while enabling SharpSK v1.6.2.2 (Is it up to date?)
java.lang.NoSuchMethodError: com.codingforcookies.armorequip.ArmorListener.<init>(Ljava/util/List;Lorg/bukkit/plugin/Plugin;)V
	at me.sharpjaws.sharpSK.main.onEnable(main.java:406) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[core.jar:git-Paper-1168]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [core.jar:git-Paper-1168]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [core.jar:git-Paper-1168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:26:20] [Server thread/INFO]: [SharpSK] Disabling SharpSK v1.6.2.2
[15:26:20] [Server thread/INFO]: [SharpSK] Successfully disabled.
```

**Comment by Sharpjaws** [comment]
Thanks I'll look into it
