### ISSUE TITLE
On Transfer Throwing error when calling Event-block for Minecart Hopper

### ISSUE THREAD

**Issue by MonoLime** [Sharpjaws/SharpSK#3]
On Transfer Throwing error when calling Event-block for Minecart Hopper

`[02:39:03 ERROR]: Could not pass event InventoryMoveItemEvent to Skript v2.2-dev16
java.lang.AbstractMethodError: Method net/minecraft/server/v1_9_R1/EntityMinecartHopper.getLocation()Lorg/bukkit/Location; is abstract
        at net.minecraft.server.v1_9_R1.EntityMinecartHopper.getLocation(SourceFile) ~[patched_1.9.2.jar:git-Paper-727]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.getLocation(CraftInventory.java:494) ~[patched_1.9.2.jar:git-Paper-727]
        at me.sharpjaws.sharpSK.main$3.get(main.java:217) ~[?:?]
        at me.sharpjaws.sharpSK.main$3.get(main.java:1) ~[?:?]
        at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:104) ~[?:?]
        at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:90) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:89) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.util.Direction$1.get(Direction.java:389) ~[?:?]
        at ch.njol.skript.util.Direction$1.get(Direction.java:1) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:159) ~[?:?]
        at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:89) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:157) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:259) ~[?:?]
        at ch.njol.skript.lang.Condition.run(Condition.java:58) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-727]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-727]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-727]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.TileEntityHopper.a(TileEntityHopper.java:395) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.TileEntityHopper.a(TileEntityHopper.java:356) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.EntityMinecartHopper.I(SourceFile:129) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.EntityMinecartHopper.m(SourceFile:120) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1728) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.World.g(World.java:1703) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1528) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:636) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:885) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by Sharpjaws** [comment]
@MonoLime Thanks for the bug report. Seems like Paperspigot is giving sharpsk a whole lot of trouble recently. Is the same error happening with normal spigot builds?

**Comment by Miic** [comment]
Yes appears to be happening on Spigot 1.9.2 as well. This is an issue with calling for event-block not reacting well with an entity's coord. Is it possible to add a check if its an entity or block triggering this event, like event-entity?

**Comment by Sharpjaws** [comment]
Ah yes that would be a good idea. It will be implemented.
